### ISSUE TITLE
Interest in collaborating with go-text?

### ISSUE THREAD

**Issue by whereswaldon** [npillmayer/uax#1]
Hi @npillmayer,

This is a valuable and ambitious project! Go sorely needs high-quality implementations of various UAX algorithms, as well as a number of other important improvements to its handling of text.

The @go-text organization is a collaboration of gophers (many from @gioui or @fyne-io) trying to improve the state of text rendering in Go. We want for GUI/Graphical applications in Go to be able to properly handle international text. We've mostly been working on text shaping, but will need good BiDi, line-breaking, and other algorithms in order to meet our goals.

Would you be interested in collaborating with us? I think we each have part of a good text stack, and putting them together may bring us much closer to a complete one.

**Comment by npillmayer** [comment]
Hi Chris,

I really appreciate your interest in UAX algorithms and -- more generally -- in good text layout.  Actually, my UAX-lib is just a by-product of my interest in text layout. I used to hope that the Go standard libary (x/text) would grow in this direction and provide more support. Unfortunately it seems this won't happen any time soon. I somewhat envy the Rust community where many text-related projects are beginning to form a serious text stack (including a Harfbuzz derivative).

To answer your question: yes, I would be willing to put some work into a joint effort for a Go text stack.

I've got a full-time day job and my OpenSource activities will always be limited, especially during stressful periods of work. Plus, I got a family to care for. Therefore I usually program in bursts, where I put a lot of effort into OpenSource in short periods of time. If there is a mode where I can be of help anyway, I'll be happy to contribute.

All the best,
--Norbert

**Comment by whereswaldon** [comment]
> I somewhat envy the Rust community where many text-related projects are beginning to form a serious text stack (including a Harfbuzz derivative).

I totally understand you here. We were in a similar position of envy until @benoitkugler actually [__source-ported all of harfbuzz to go__](https://github.com/benoitkugler/textlayout/tree/main/harfbuzz).

Now that we have a good shaper (it passes upstream harfbuzz's test suite), we're filling in the gaps elsewhere. I'm currently working on paragraph layout, so principally where/how to break lines. Your implementation of UAX#14 has already saved me a bunch of time, and the look of your other libraries suggests to me that we will benefit still more when it's time to add those features.

> I've got a full-time day job and my OpenSource activities will always be limited, especially during stressful periods of work. Plus, I got a family to care for. Therefore I usually program in bursts, where I put a lot of effort into OpenSource in short periods of time. If there is a mode where I can be of help anyway, I'll be happy to contribute.

Totally understand. :D 

Honestly, your UAX implementations as they already exist are a colossal help. Possible ways for you to collaborate include:

- Answering questions from your UAX domain expertise about how to apply these algorithms and about as-yet-unimplemented capabilities.
- Providing your input on discussions of how to advance text handling in go.
- Reviewing PRs to your algorithms if we find that we need them extended.

Please feel free to join the `ui-text-rendering` channel in `gophers.slack.com` if you'd like to participate in the real-time conversations over there. You can also watch the repos in @go-text to stay in the loop on conversations. I've already invited you to join the Org, but I don't think that will automatically notify you of conversations there.

**Comment by npillmayer** [comment]
Joined the channel. Will follow development with interest.
Closing this issue.
